export const productArray = [
    {
        name:"Ignis",
        description:"",
        id: "1",
        image:"../images/Ignis.jpg",
        price: "2000kr",
        latest: true,
        size: "",
        created: "",
        alt: "",
        sold: false,
    },
    {
        name:"Verão",
        description:"",
        id: "1",
        image:"../images/Verão.jpg",
        price: "2000kr",
        latest: true,
        size: "",
        created: "",
        alt: "",
        sold: false,
    },
    {
        name:"Amnis",
        description:"",
        id: "1",
        image:"../images/Amnis.jpg",
        price: "2000kr",
        latest: true,
        size: "",
        created: "",
        alt: "",
        sold: false,
    },
    {
        name:"Arancia",
        description:"#",
        id: "2",
        image:"../images/Arancia.jpg",
        price: "2000kr",
        latest: false,
        size: "#",
        created: "#",
        alt: "#",
        sold: false,
    },
    {
        name:"Astro",
        description:"#",
        id: "#",
        image:"../images/Astro.jpg",
        price: "2000kr",
        latest: false,
        size: "#",
        created: "#",
        alt: "#",
        sold: false,
    },
    {
        name:"Dividir",
        description:"#",
        id: "#",
        image:"../images/Dividir.jpg",
        price: "#",
        latest: false,
        size: "#",
        created: "#",
        alt: "#",
        sold: false,
    },
    {
        name:"Fluctus",
        description:"#",
        id: "#",
        image:"../images/Fluctus.jpg",
        price: "#",
        latest: false,
        size: "#",
        created: "#",
        alt: "#",
        sold: false,
    },
    {
        name:"Silva",
        description:"#",
        id: "#",
        image:"../images/Silva.jpg",
        price: "#",
        latest: false,
        size: "#",
        created: "#",
        alt: "#",
        sold: false,
    },
    {
        name:"Ondas",
        description:"#",
        id: "#",
        image:"../images/Ondas.jpg",
        price: "#",
        latest: false,
        size: "#",
        created: "#",
        alt: "#",
        sold: false,
    },
    {
        name:"Silvis II",
        description:"#",
        id: "#",
        image:"../images/Silvis II.jpg",
        price: "#",
        latest: false,
        size: "#",
        created: "#",
        alt: "#",
        sold: false,
    },
    {
        name:"Umbra",
        description:"#",
        id: "#",
        image:"../images/Umbra.jpg",
        price: "#",
        latest: false,
        size: "#",
        created: "#",
        alt: "#",
        sold: false,
    },
    {
        name:"Silvis",
        description:"#",
        id: "#",
        image:"../images/Silvis.jpg",
        price: "#",
        latest: false,
        size: "#",
        created: "#",
        alt: "#",
        sold: false,
    },
    {
        name:"Ventus",
        description:"#",
        id: "#",
        image:"../images/Ventus.jpg",
        price: "#",
        latest: false,
        size: "#",
        created: "#",
        alt: "#",
        sold: false,
    },
]